name: '📦 Create Installers'
description: 'Create MSI installers using Advanced Installer for all platforms'

inputs:
  app-name:
    description: 'Application name for packaging'
    required: true
  app-version:
    description: 'Application version'
    required: true
  advinst-license:
    description: 'Advanced Installer license key (optional - required only for non-simple projects)'
    required: false
  workflow-type:
    description: 'Type of workflow (nightly or release)'
    required: false
    default: 'nightly'
  artifacts-path:
    description: 'Path to build artifacts'
    required: false
    default: '.'

outputs:
  x86-installer:
    description: 'Path to x86 MSI installer'
    value: ${{ github.workspace }}/setup/output/${{ inputs.app-name }}-${{ inputs.app-version }}-x86.msi
  x64-installer:
    description: 'Path to x64 MSI installer'
    value: ${{ github.workspace }}/setup/output/${{ inputs.app-name }}-${{ inputs.app-version }}-x64.msi
  arm64-installer:
    description: 'Path to ARM64 MSI installer'
    value: ${{ github.workspace }}/setup/output/${{ inputs.app-name }}-${{ inputs.app-version }}-ARM64.msi

runs:
  using: "composite"
  steps:
    - name: 📥 Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: "${{ inputs.app-name }}-${{ inputs.app-version }}-*"
        merge-multiple: false
        path: ${{ inputs.artifacts-path }}/artifacts

    - name: 📂 Display Downloaded Artifacts Structure
      shell: pwsh
      run: |
        Write-Host "🔍 Examining downloaded artifacts..."
        Get-ChildItem -Path "${{ inputs.artifacts-path }}/artifacts" -Recurse | ForEach-Object {
          $relativePath = $_.FullName.Replace("${{ inputs.artifacts-path }}/artifacts", "")
          Write-Host "  $relativePath"
        }

    - name: 📦 Prepare Publish Directories
      shell: pwsh
      run: |
        Write-Host "🔧 Setting up publish directories for Advanced Installer..."

        # Create the expected directory structure for Advanced Installer
        $publishBase = "src/Bucket.App/bin"
        New-Item -ItemType Directory -Path "$publishBase/win-x86/publish" -Force
        New-Item -ItemType Directory -Path "$publishBase/win-x64/publish" -Force
        New-Item -ItemType Directory -Path "$publishBase/win-arm64/publish" -Force

        # Copy artifacts to expected locations
        $artifactsPath = "${{ inputs.artifacts-path }}/artifacts"

        if (Test-Path "$artifactsPath/${{ inputs.app-name }}-${{ inputs.app-version }}-x86") {
          Write-Host "📁 Copying x86 artifacts..."
          Copy-Item -Path "$artifactsPath/${{ inputs.app-name }}-${{ inputs.app-version }}-x86/*" -Destination "$publishBase/win-x86/publish/" -Recurse -Force
        }

        if (Test-Path "$artifactsPath/${{ inputs.app-name }}-${{ inputs.app-version }}-x64") {
          Write-Host "📁 Copying x64 artifacts..."
          Copy-Item -Path "$artifactsPath/${{ inputs.app-name }}-${{ inputs.app-version }}-x64/*" -Destination "$publishBase/win-x64/publish/" -Recurse -Force
        }

        if (Test-Path "$artifactsPath/${{ inputs.app-name }}-${{ inputs.app-version }}-ARM64") {
          Write-Host "📁 Copying ARM64 artifacts..."
          Copy-Item -Path "$artifactsPath/${{ inputs.app-name }}-${{ inputs.app-version }}-ARM64/*" -Destination "$publishBase/win-arm64/publish/" -Recurse -Force
        }

    - name: 🔍 Check License Availability
      shell: pwsh
      run: |
        $license = "${{ inputs.advinst-license }}"
        if ([string]::IsNullOrEmpty($license)) {
          Write-Host "⚠️ No Advanced Installer license provided - will attempt to build with simple project only"
          echo "HAS_LICENSE=false" >> $env:GITHUB_ENV
        } else {
          Write-Host "✅ Advanced Installer license provided"
          echo "HAS_LICENSE=true" >> $env:GITHUB_ENV
        }

    - name: 🏗️ Build x86 Installer with Advanced Installer (With License)
      if: env.HAS_LICENSE == 'true'
      id: build-x86-licensed
      uses: caphyon/advinst-github-action@main
      with:
        advinst-version: '23.0'
        advinst-license: ${{ inputs.advinst-license }}
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}/setup/Bucket.Setup_x86/Bucket.Setup_x86.aip
        aip-build-name: 'DefaultBuild'
        aip-package-name: '${{ inputs.app-name }}-${{ inputs.app-version }}-x86.msi'
        aip-output-dir: ${{ github.workspace }}/setup/output
        aip-commands: |
          SetVersion ${{ inputs.app-version }}
          SetPackageName ${{ inputs.app-name }}-${{ inputs.app-version }}-x86.msi

    - name: 🏗️ Build x86 Installer with Advanced Installer (No License)
      if: env.HAS_LICENSE == 'false'
      id: build-x86-unlicensed
      uses: caphyon/advinst-github-action@main
      with:
        advinst-version: '23.0'
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}/setup/Bucket.Setup_x86/Bucket.Setup_x86.aip
        aip-build-name: 'DefaultBuild'
        aip-package-name: '${{ inputs.app-name }}-${{ inputs.app-version }}-x86.msi'
        aip-output-dir: ${{ github.workspace }}/setup/output
        aip-commands: |
          SetVersion ${{ inputs.app-version }}
          SetPackageName ${{ inputs.app-name }}-${{ inputs.app-version }}-x86.msi

    - name: 🏗️ Build x64 Installer with Advanced Installer (With License)
      if: env.HAS_LICENSE == 'true'
      id: build-x64-licensed
      uses: caphyon/advinst-github-action@main
      with:
        advinst-version: '23.0'
        advinst-license: ${{ inputs.advinst-license }}
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}/setup/Bucket.Setup_x64/Bucket.Setup_x64.aip
        aip-build-name: 'DefaultBuild'
        aip-package-name: '${{ inputs.app-name }}-${{ inputs.app-version }}-x64.msi'
        aip-output-dir: ${{ github.workspace }}/setup/output
        aip-commands: |
          SetVersion ${{ inputs.app-version }}
          SetPackageName ${{ inputs.app-name }}-${{ inputs.app-version }}-x64.msi

    - name: 🏗️ Build x64 Installer with Advanced Installer (No License)
      if: env.HAS_LICENSE == 'false'
      id: build-x64-unlicensed
      uses: caphyon/advinst-github-action@main
      with:
        advinst-version: '23.0'
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}/setup/Bucket.Setup_x64/Bucket.Setup_x64.aip
        aip-build-name: 'DefaultBuild'
        aip-package-name: '${{ inputs.app-name }}-${{ inputs.app-version }}-x64.msi'
        aip-output-dir: ${{ github.workspace }}/setup/output
        aip-commands: |
          SetVersion ${{ inputs.app-version }}
          SetPackageName ${{ inputs.app-name }}-${{ inputs.app-version }}-x64.msi

    - name: 🏗️ Build ARM64 Installer with Advanced Installer (With License)
      if: env.HAS_LICENSE == 'true'
      id: build-arm64-licensed
      uses: caphyon/advinst-github-action@main
      with:
        advinst-version: '23.0'
        advinst-license: ${{ inputs.advinst-license }}
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}/setup/Bucket.Setup_arm64/Bucket.Setup_arm64.aip
        aip-build-name: 'DefaultBuild'
        aip-package-name: '${{ inputs.app-name }}-${{ inputs.app-version }}-ARM64.msi'
        aip-output-dir: ${{ github.workspace }}/setup/output
        aip-commands: |
          SetVersion ${{ inputs.app-version }}
          SetPackageName ${{ inputs.app-name }}-${{ inputs.app-version }}-ARM64.msi

    - name: 🏗️ Build ARM64 Installer with Advanced Installer (No License)
      if: env.HAS_LICENSE == 'false'
      id: build-arm64-unlicensed
      uses: caphyon/advinst-github-action@main
      with:
        advinst-version: '23.0'
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}/setup/Bucket.Setup_arm64/Bucket.Setup_arm64.aip
        aip-build-name: 'DefaultBuild'
        aip-package-name: '${{ inputs.app-name }}-${{ inputs.app-version }}-ARM64.msi'
        aip-output-dir: ${{ github.workspace }}/setup/output
        aip-commands: |
          SetVersion ${{ inputs.app-version }}
          SetPackageName ${{ inputs.app-name }}-${{ inputs.app-version }}-ARM64.msi

    - name: 📦 Upload Installer Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: '${{ inputs.workflow-type }}-installer-all-platforms'
        path: |
          ${{ github.workspace }}/setup/output/${{ inputs.app-name }}-${{ inputs.app-version }}-x86.msi
          ${{ github.workspace }}/setup/output/${{ inputs.app-name }}-${{ inputs.app-version }}-x64.msi
          ${{ github.workspace }}/setup/output/${{ inputs.app-name }}-${{ inputs.app-version }}-ARM64.msi
        retention-days: 90

    - name: 📊 Display Installer Information
      shell: pwsh
      run: |
        Write-Host "🎉 Advanced Installer build completed successfully!"
        Write-Host ""
        Write-Host "📦 Generated Installers:"

        $outputDir = "${{ github.workspace }}/setup/output"
        if (Test-Path $outputDir) {
          Get-ChildItem -Path $outputDir -Filter "*.msi" | ForEach-Object {
            $sizeKB = [math]::Round($_.Length / 1KB, 2)
            Write-Host "  📄 $($_.Name) ($sizeKB KB)"
          }
        } else {
          Write-Host "⚠️ Output directory not found: $outputDir"
        }
