name: 'Setup Environment'
description: 'Setup build environment with .NET 9 SDK, MSBuild and Advanced Installer'
inputs:
  dotnet-version:
    description: '.NET SDK version to use'
    required: false
    default: '9.0.x'
  msbuild-architecture:
    description: 'MSBuild architecture'
    required: false
    default: 'x64'
  advanced-installer-version:
    description: 'Advanced Installer version'
    required: false
    default: 'latest'
  advanced-installer-license:
    description: 'Advanced Installer license key'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: ${{ inputs.msbuild-architecture }}

    - name: Setup Advanced Installer
      uses: caphyon/advinst-github-action@main
      with:
        advinst-version: ${{ inputs.advanced-installer-version }}
        advinst-license: ${{ inputs.advanced-installer-license }}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Display environment info
      shell: pwsh
      run: |
        Write-Host "=== Environment Information ===" -ForegroundColor Cyan
        Write-Host "OS: $env:OS"
        Write-Host "Runner OS: $env:RUNNER_OS"
        Write-Host ""

        Write-Host "=== .NET SDK Information ===" -ForegroundColor Green
        dotnet --list-sdks
        dotnet --version
        Write-Host ""

        Write-Host "=== MSBuild Information ===" -ForegroundColor Green
        msbuild -version
        Write-Host ""

        Write-Host "=== NuGet Information ===" -ForegroundColor Green
        nuget help | Select-Object -First 1
