global using Bucket.App.Common;
global using Bucket.App.ViewModels;
global using Bucket.App.Views;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using DevWinUI;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using static Bucket.App.Common.AppHelper;
global using static Bucket.App.Common.LoggerSetup;