name: 🌙 Nightly Build

# Global configuration - modify these to change default behavior
env:
  SKIP_TESTS_DEFAULT: true  # Set to true to skip tests by default for scheduled runs

on:
  schedule:
    # Run at 2:00 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      force-build:
        description: 'Force build even if no changes'
        required: false
        type: boolean
        default: false
      skip-tests:
        description: 'Skip running tests'
        required: false
        type: boolean
        default: false

# Only run on dev branch
jobs:
  check-changes:
    name: 🔍 Check for Changes
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
      version: ${{ steps.version.outputs.version }}
      msi_version: ${{ steps.version.outputs.msi_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: dev

      - name: Check for merged PRs since last tag
        id: check
        shell: pwsh
        run: |
          Write-Host "Checking for merged PRs since last tag..." -ForegroundColor Cyan

          # Get the latest release tag (any type)
          $latestTag = git tag -l --sort=-version:refname | Select-Object -First 1
          Write-Host "Latest release: $latestTag" -ForegroundColor Yellow

          if ([string]::IsNullOrEmpty($latestTag)) {
            Write-Host "No previous tags found, building first nightly" -ForegroundColor Green
            echo "should-build=true" >> $env:GITHUB_OUTPUT
          } else {
            # Get all merged PRs since last tag (only merge commits from PRs)
            $mergedPRs = git log --merges --grep="Merge pull request" --pretty=format:"%h %s" "$latestTag..dev" 2>$null

            if ([string]::IsNullOrEmpty($mergedPRs)) {
              $mergeCount = 0
            } else {
              $mergeCount = ($mergedPRs | Select-String "Merge pull request").Count
            }

            if ($mergeCount -eq 0) {
              if ("${{ github.event.inputs.force-build }}" -eq "true") {
                Write-Host "No PRs merged since last tag, but force build requested" -ForegroundColor Yellow
                echo "should-build=true" >> $env:GITHUB_OUTPUT
              } else {
                Write-Host "No PRs merged to dev since last tag. Skipping build." -ForegroundColor Yellow
                echo "should-build=false" >> $env:GITHUB_OUTPUT
              }
            } else {
              Write-Host "Merged PRs since last tag (dev):" -ForegroundColor Green
              Write-Host $mergedPRs

              # Check if only change is a release PR merge (skip in that case)
              if ($mergeCount -eq 1 -and $mergedPRs -like "*release/*") {
                Write-Host "Only change since last tag is a release PR merge. Skipping build." -ForegroundColor Yellow
                echo "should-build=false" >> $env:GITHUB_OUTPUT
              } else {
                echo "should-build=true" >> $env:GITHUB_OUTPUT
              }
            }
          }

      - name: Generate version
        id: version
        if: steps.check.outputs.should-build == 'true'
        shell: pwsh
        run: |
          # Generate version in format YY.MM.DD-Nightly or YY.MM.DD.BUILD-Nightly for Git tag
          # and YY.M.D.BUILD for MSI (Windows Installer compatible)
          $date = Get-Date -Format "yy.MM.dd"
          $dateMsi = Get-Date -Format "yy.M.d"  # Remove leading zeros for MSI compatibility
          Write-Host "Base date: $date (Git tag format)" -ForegroundColor Cyan
          Write-Host "Base date MSI: $dateMsi (MSI version format)" -ForegroundColor Cyan

          # Check if we already have a nightly for today (without build number)
          $baseNightlyExists = (git tag -l "v$date-Nightly" | Measure-Object).Count

          if ($baseNightlyExists -eq 0) {
            # First nightly of the day
            $gitVersion = "$date-Nightly"
            $msiVersion = "$dateMsi.1"  # Add .1 for nightly builds to distinguish from releases
            Write-Host "First nightly of the day: $gitVersion (Git) / $msiVersion (MSI)" -ForegroundColor Green
          } else {
            # Additional nightly (hotfix), find next build number
            $buildNum = 2
            while (git tag -l "v$date.$buildNum-Nightly" | Where-Object { $_ -eq "v$date.$buildNum-Nightly" }) {
              $buildNum++
            }
            $gitVersion = "$date.$buildNum-Nightly"
            $msiVersion = "$dateMsi.$buildNum"
            Write-Host "Nightly hotfix build: $gitVersion (Git) / $msiVersion (MSI)" -ForegroundColor Yellow
          }

          Write-Host "Generated Git version: $gitVersion" -ForegroundColor Green
          Write-Host "Generated MSI version: $msiVersion" -ForegroundColor Green
          echo "version=$gitVersion" >> $env:GITHUB_OUTPUT
          echo "msi_version=$msiVersion" >> $env:GITHUB_OUTPUT

  # run-tests:
  #   name: Run Tests
  #   needs: [check-changes]
  #   if: |
  #     needs.check-changes.outputs.should-build == 'true' &&
  #     ((github.event_name == 'workflow_dispatch' && github.event.inputs.skip-tests != 'true') ||
  #     (github.event_name != 'workflow_dispatch' && env.SKIP_TESTS_DEFAULT == 'false'))
  #   uses: ./.github/workflows/action_run-tests.yml
  #   with:
  #     configuration: 'Release'
  #     platforms: 'x64,x86,ARM64'
  #     generate-coverage: 'true'
  #     checkout-ref: 'dev'

  build-and-package:
    name: 🏗️ Build, Package and Create Installers
    needs: [check-changes]
    if: needs.check-changes.outputs.should-build == 'true'
    uses: ./.github/workflows/action_build-package-installers.yml
    with:
      configuration: 'Release'
      version: ${{ needs.check-changes.outputs.msi_version }}
      create-zip: 'true'
      checkout-ref: 'dev'

  create-release:
    name: 📦 Create Release
    needs: [check-changes, build-and-package]
    if: needs.check-changes.outputs.should-build == 'true'
    permissions:
      contents: write
      actions: read
    uses: ./.github/workflows/action_release-management.yml
    with:
      version: ${{ needs.check-changes.outputs.version }}
      is-prerelease: 'true'
      artifacts-path: 'artifacts'
      checkout-ref: 'dev'
      release-notes: |
        This is an **automated nightly build** created from the latest changes in the dev branch.

        ⚠️ **Warning**: This build may contain unstable features and is intended for testing purposes only.
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  cleanup-old-releases:
    name: 🧹 Cleanup Old Releases
    needs: [check-changes, create-release]
    if: needs.check-changes.outputs.should-build == 'true' && success()
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Cleanup old nightly releases
        shell: pwsh
        run: |
          Write-Host "Cleaning up old nightly releases..." -ForegroundColor Cyan

          # Keep only the last 7 nightly releases
          $nightlyReleases = gh release list --limit 100 --json tagName,isPrerelease,createdAt |
            ConvertFrom-Json |
            Where-Object { $_.isPrerelease -and $_.tagName -like "*-Nightly" } |
            Sort-Object createdAt -Descending

          if ($nightlyReleases.Count -gt 7) {
            $toDelete = $nightlyReleases | Select-Object -Skip 7

            foreach ($release in $toDelete) {
              Write-Host "Deleting old nightly release: $($release.tagName)" -ForegroundColor Yellow
              try {
                gh release delete $release.tagName --yes --cleanup-tag
              } catch {
                Write-Host "Failed to delete $($release.tagName): $($_.Exception.Message)" -ForegroundColor Red
                exit 1
              }
            }

            Write-Host "Cleanup complete. Kept the 7 most recent nightly builds." -ForegroundColor Green
            exit 0
          } else {
            Write-Host "No cleanup needed. Current nightly releases: $($nightlyReleases.Count)" -ForegroundColor Green
            exit 0
          }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  summary:
    name: 📋 Summary
    needs: [check-changes, create-release, cleanup-old-releases]
    if: always() && needs.check-changes.outputs.should-build == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Generate summary
        shell: pwsh
        run: |
          Write-Host "# 🌙 Nightly Build Summary" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "## Build Information" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "- **Git Version**: ${{ needs.check-changes.outputs.version }}" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "- **MSI Version**: ${{ needs.check-changes.outputs.msi_version }}" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "- **Branch**: dev" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "- **Status**: ${{ needs.create-release.result }}" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "" >> $env:GITHUB_STEP_SUMMARY

          if ("${{ needs.create-release.result }}" -eq "success") {
            Write-Host "✅ **Nightly build completed successfully!**" >> $env:GITHUB_STEP_SUMMARY
            Write-Host "" >> $env:GITHUB_STEP_SUMMARY
            Write-Host '[View Release](https://github.com/${{ github.repository }}/releases/tag/v${{ needs.check-changes.outputs.version }})' >> $env:GITHUB_STEP_SUMMARY
          } else {
            Write-Host "❌ **Nightly build failed!**" >> $env:GITHUB_STEP_SUMMARY
          }


  notify-skip:
    name: ⏭️ Notify Skip
    needs: check-changes
    if: needs.check-changes.outputs.should-build == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Skip notification
        shell: pwsh
        run: |
          Write-Host "# ⏭️ Nightly Build Skipped" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "No changes detected in the last 24 hours on the dev branch." >> $env:GITHUB_STEP_SUMMARY
          Write-Host "The nightly build has been skipped to save resources." >> $env:GITHUB_STEP_SUMMARY
          Write-Host "" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "To force a build, you can:" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "1. Manually trigger this workflow with 'Force build' option" >> $env:GITHUB_STEP_SUMMARY
          Write-Host "2. Push new commits to the dev branch" >> $env:GITHUB_STEP_SUMMARY
