name: Manual NuGet Update

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages spécifiques à mettre à jour (séparés par des virgules, laisser vide pour tous)'
        required: false
        type: string
      target_versions:
        description: 'Versions cibles spécifiques (optionnel)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  manual-nuget-update:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Install dotnet-outdated tool
      run: dotnet tool install --global dotnet-outdated-tool

    - name: Update specific packages or all packages
      shell: pwsh
      run: |
        $packages = "${{ github.event.inputs.packages }}"

        if ([string]::IsNullOrWhiteSpace($packages)) {
          Write-Host "Mise à jour de tous les packages..."
          dotnet outdated --upgrade
        } else {
          Write-Host "Mise à jour des packages spécifiés: $packages"
          $packageList = $packages -split ","
          foreach ($package in $packageList) {
            $trimmedPackage = $package.Trim()
            Write-Host "Mise à jour du package: $trimmedPackage"
            dotnet add package $trimmedPackage
          }
        }

    - name: Build solution to verify updates
      run: dotnet build --configuration Release --no-restore

    - name: Run tests to verify updates
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Create summary
      shell: pwsh
      run: |
        .\.github\scripts\create-manual-summary.ps1 -Packages "${{ github.event.inputs.packages }}" -TargetVersions "${{ github.event.inputs.target_versions }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: mise à jour manuelle des packages NuGet"
        title: "🔧 Mise à jour manuelle des packages NuGet"
        body-path: manual-updates-summary.md
        branch: manual/nuget-updates-${{ github.run_number }}
        delete-branch: true
        assignees: ${{ github.repository_owner }}
        labels: |
          dependencies
          manual-pr
          nuget
